% This script loads and plots subfigures of difference slices of
% an ITALCS3Datmo 3D FTLE map/tracer set. Plotting Fig 5 of 2026 ITALCS3D
% manuscript.
%
% S. Datta-Barua
% 7 Oct 2026 Preparing for publication to github.

clear

% Specify the path where the ITALCS3D run resultant netcdf files were placed.
run_folder = '/path/to/italcs3d/output/';

% Option 1 for input FTLE maps
% Specify the date that the ITALCS3D run was completed.
date_of_run{1} = 'yymmdd'; %'261007'; %
date_of_run{2} = 'yymmdd'; %'261007'; %

% Filenames of FTLE.nc files generated by waccm_italcs3d_script.m
fname{1} = [ run_folder date_of_run{1} '_runs/WACCMX+DART_ITALCS3Datmo_20090125_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
fname{2} = [ run_folder date_of_run{2} '_runs/WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Option 2 for FTLE maps
% Alternatively, use the files posted to zenodo.
fname{1} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090125_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
fname{2} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Specify a figure output path.
output_dir = '/path/to/figure/output/folder/';
if ~exist(output_dir,'dir')
    mkdir(output_dir)
end
%---------------------
% No need to change anything below here.

FTLE_flag = 1;
tracer_flag = 1;
plev_flag = 0;
lon_plane = 315; % deg E
lat_plane = 65; % deg N
highres_flag = 2;
% Set filterstr for filename saving.
if highres_flag == 2
    filterstr = 'hrlyassim';
elseif highres_flag == 1
    filterstr = 'highres';
else
    filterstr = '6hrassim';
end

J_in_Cartesian_flag = 1;%[0 2 1 1]; % True if you want to transform to Jtilde, otherwise false.
prefixstr = 'abcd';

lat = ncread(fname{1}, 'lat');
lon = ncread(fname{1}, 'lon');
plev = ncread(fname{1},'plev');

tiledlayout(2,2, 'Padding', 'compact', 'TileSpacing', 'compact');
for filenum = 1:2
    % First the polar map.
    subplot_idx = 1;
    nexttile;

    clear FTLE_Value tracer_pos
    FTLE_Value = ncread(fname{filenum}, 'FTLE');
    t0(filenum) = ncread(fname{filenum}, 't0');

    try
    	ht = ncread(fname{filenum}, 'ht');
    	htrow = find(abs(ht(1,1,:,1) - tarht) == min(abs(ht(1,1,:,1) - tarht)));
    catch
    	htrow = 57;
    end

    try
    	tracer_pos = ncread(fname{filenum}, 'tracer_pos');
    catch
    	tracerlat = ncread(fname{filenum}, 'tracerlat');
    	tracerlon = ncread(fname{filenum}, 'tracerlon');
    	tracer_pos(:,2,:) = tracerlat;
    	tracer_pos(:,1,:) = tracerlon;
    end



    if ~exist('modelstr', 'var')
    	modelstr = 'WACCMX+DART';
    end
    if ~exist('trueht', 'var')
    	trueht = 90; %km
    	tarht = 90e3; %m
    end
    if ~exist('regionstr', 'var')
    	regionstr = 'North Pole';
    	origin = [90, 0]; % plot north pole at the center, 0 UT local time at the bottom
    end
    try
    	ncread(fname{filenum}, 'filterstr');
    catch
    	filterstr = '';
    end

    try
        integration_hours = ncread(fname{filenum}, 'integration_hours');
    catch
        integration_hours = [24];%[24; 24; 24];
    end
    try
    	FTLE_flag = ncread(fname{filenum}, 'FTLE_flag');
    catch
    	FTLE_flag = 1;
    end


    % Fig a: hourly WACCMX+DART data 01/25/09, run with ITALCS3Datmo called by waccm_3d_script_pleiades.m.
    %subplot(2,2,subplot_idx)
    if FTLE_flag % Plot a polar map with the FTLE and continents, and colorbar.
    	if ndims(FTLE_Value) < 3 % FTLE_Value [96 x 145 x 126] nlat x nlon x nlev
    	    h = plot_polar_ftle_map(['(' prefixstr((filenum-1)*2 + subplot_idx) ') ' modelstr], t0(filenum), lat, lon, trueht, FTLE_Value(:,:,1), regionstr, integration_hours(1), J_in_Cartesian_flag(subplot_idx));
    	else
    	    FTLE_Value_htslice = squeeze(FTLE_Value(:,:,htrow));
            h = plot_polar_ftle_map(['(' prefixstr((filenum-1)*2 + subplot_idx) ') ' modelstr], t0(filenum), lat, lon, tarht, FTLE_Value_htslice, regionstr, integration_hours, J_in_Cartesian_flag(subplot_idx));
        end
    else % Plot a plain map with continents.
    	h = plot_polar_map(modelstr, t0(filenum), lat, lon, tarht, regionstr, integration_hours(i));
    end
    if tracer_flag
    	% Input arguments should be [ntimes x ntracers].
    	hA = plot_tracers_on_map(squeeze(tracer_pos(:,2,:)), squeeze(tracer_pos(:,1,:)));
    end

    % Subplot (b): lon-alt plane at 65 deg N.
    nexttile;
    subplot_idx = 2;

    % Plot the zonal plane with FTLE values on it.
    if FTLE_flag
    	% Find the latitudinal plane closest to the desired plane.
    	lat_ind = find(abs(lat - lat_plane) == min(abs(lat - lat_plane)));
    	% Set this matrix to be nlev x nlon.
    	FTLE_Value_latslice = squeeze(FTLE_Value(lat_ind,:,:))';
    	% Need to be double or function delaunay doesn't work.
    	% Also needs to be nlev x nlon
    	ht_inlatplane = double(squeeze(ht(:,lat_ind,:,1)))';
    	h = plot_zonal_ftle_map(['(' prefixstr((filenum-1)*2+subplot_idx) ') ' modelstr], t0(filenum), plev, ht_inlatplane, lon, FTLE_Value_latslice, lat_plane);%, tracer_pos);
    end % if FTLE_flag
    if tracer_flag
    	% Convert vertical units to km if z coordinate is gph.
    	if plev_flag
            hA = plot_tracers(squeeze(tracer_pos(:,1,:)), ...
            	squeeze(tracer_pos(:,3,:)));
    	    ylabel('Pressure level [hPa]')
        else
    	    hA = plot_tracers_unwrapped(squeeze(tracer_pos(:,1,:)), ...
            	squeeze(tracer_pos(:,3,:)/1e3));
    		ylabel('Geopotential height [km]')
    	end % if plev_flag
    	xlabel('Longitude [deg]')
    end	% if tracer_flag
end % for filenum = 1:2

figfile = [output_dir datestr(now,'yymmdd') '_' ...
    modelstr '_' ...
    num2str(tarht/1e3) 'km_ftle_' filterstr 'compare_' ...
    datestr(t0(1), 'yymmdd_hhMM') '_' ...
    datestr(t0(2), 'yymmdd_hhMM') '_' ...
    '.fig'];
saveas(gcf,[figfile(1:end-3) 'png'], 'png')
close
