% This script loads and plots subfigures of difference slices of 
% an ITALCS3Datmo 3D FTLE map/tracer set with WACCMX+DART and SABER data
% contour lines over them.  Makes Figs. 6-7 of the 2026 ITALCS3D
% manuscript.
%
% S. Datta-Barua
% 7 Oct 2026 Preparing for publication to github.

clear

% Specify the path where the ITALCS3D run resultant netcdf files were placed.
run_folder = '/path/to/italcs3d/output/';

% Option 1 for input FTLE maps
% Specify the date that the ITALCS3D run was completed.
date_of_run{1} = 'yymmdd'; %'261007'; %
date_of_run{2} = 'yymmdd'; %'261007'; %

% Filenames of FTLE.nc files generated by waccm_italcs3d_script.m
fname{1} = [ run_folder date_of_run{1} '_runs/WACCMX+DART_ITALCS3Datmo_20090125_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
fname{2} = [ run_folder date_of_run{2} '_runs/WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Option 2 for FTLE maps
% Alternatively, use the files posted to zenodo.
fname{1} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090125_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
fname{2} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Load WACCMX+DART data.
% Hourly assimilation of data.
input_dir = '/path/to/waccmx_dart/files/'; 
ncfilename{1} = [input_dir, 'waccmx_dart_h2o_2009.cam.h1.ensmean.2009-01-25-00000.nc'];
ncfilename{2} = [input_dir, 'waccmx_dart_h2o_2009.cam.h1.ensmean.2009-01-29-00000.nc'];

% Load SABER data downloaded from https://data.gats-inc.com/saber/
saberFolder = '/path/to/saber/data/';
saber{1} = [saberFolder 'xz_saber+merra2_65N_20090125.nc'];
saber{2} = [saberFolder 'xz_saber+merra2_65N_20090129.nc'];
saber{3} = [saberFolder 'yz_saber+merra2_315E_20090125.nc'];
saber{4} = [saberFolder 'yz_saber+merra2_315E_20090129.nc'];


% Specify a figure output path.
output_dir = '/path/to/figure/output/folder/';
if ~exist(output_dir,'dir')
    mkdir(output_dir)
end
%---------------------
% No need to change anything below here.
FTLE_flag = 1;
tracer_flag = 0;
plev_flag = 0;
lon_plane = 315; % deg E
lat_plane = 65; % deg N
highres_flag = 2;
% Set filterstr for filename saving.
if highres_flag == 2
	filterstr = 'hrlyassim';
elseif highres_flag == 1
	filterstr = 'highres';
else
	filterstr = '6hrassim';
end

J_in_Cartesian_flag = 1;%[0 2 1 1]; % True if you want to transform to Jtilde, otherwise false.
prefixstr = 'abcd';

lat = ncread(fname{1}, 'lat');
lon = ncread(fname{1}, 'lon');
plev = ncread(fname{1},'plev');

% Prepare two figs
% Lon-alt eddy GPH plot.
figure(1)
set(gcf, 'Position', [100 100 400 600]);
tiledlayout(4,1, 'Padding', 'compact', 'TileSpacing', 'compact');
% Lat-alt zonal mean u plot.
figure(2)
set(gcf, 'Position', [100 100 400 600]);
tiledlayout(4,1, 'Padding', 'compact', 'TileSpacing', 'compact');

% Loop through FTLE files
for filenum = 1:2
    clear FTLE_Value tracer_pos
    if FTLE_flag
    	FTLE_Value = ncread(fname{filenum}, 'FTLE');
    end
    t0(filenum) = ncread(fname{filenum}, 't0');

    try
	ht = ncread(fname{filenum}, 'ht');
	htrow = find(abs(ht(1,1,:,1) - tarht) == min(abs(ht(1,1,:,1) - tarht)));
    catch
	htrow = 57;
    end

    if tracer_flag    
    	try
	    tracer_pos = ncread(fname{filenum}, 'tracer_pos');
    	catch
	    tracerlat = ncread(fname{filenum}, 'tracerlat');
	    tracerlon = ncread(fname{filenum}, 'tracerlon');
	    tracer_pos(:,2,:) = tracerlat;
	    tracer_pos(:,1,:) = tracerlon;
    	end
    end
    
    if ~exist('modelstr', 'var')
	modelstr = 'WACCMX+DART';
    end
    if ~exist('trueht', 'var')
	trueht = 90; %km
	tarht = 90e3; %m
    end
    try
	ncread(fname{filenum}, 'filterstr');
    catch
	filterstr = '';
    end

    try
	integration_hours = ncread(fname{filenum}, 'integration_hours');
    catch
	integration_hours = [24];%[24; 24; 24];
    end
    try
	FTLE_flag = ncread(fname{filenum}, 'FTLE_flag');
    catch
	FTLE_flag = 1;
    end

    output_dir = [getenv('HOME') '/mfigs/lcs/' modelstr '/' ...
	datestr(now,'yymmdd') '/'];
    if ~exist(output_dir,'dir')
	mkdir(output_dir)
    end
% Get plot titles correct.
datasource_str = {' WACCMX+DART', ' SABER'};
contour_str = {' eddy GPH with', ' mean zonal wind'};

    % First the lon-alt map.
    fignum = 1;
    figure(fignum)
    % Make two subplots with same FTLE map.
    for subplotind = 1:2
    	nexttile;
        combo_idx = (filenum-1)*2+subplotind;

	% Plot the zonal plane with FTLE values on it.
    	if FTLE_flag
		% Find the latitudinal plane closest to the desired plane.
		lat_ind = find(abs(lat - lat_plane) == min(abs(lat - lat_plane)));
		% Set this matrix to be nlev x nlon.
		FTLE_Value_latslice = squeeze(FTLE_Value(lat_ind,:,:))';
		% Need to be double or function delaunay doesn't work.
		% Also needs to be nlev x nlon 
		ht_inlatplane = double(squeeze(ht(:,lat_ind,:,1)))';
		h = plot_zonal_ftle_map(['(' prefixstr(combo_idx) ')' ...
		datasource_str{subplotind} contour_str{fignum} ... modelstr
		], t0(filenum), plev, ht_inlatplane, lon, FTLE_Value_latslice, lat_plane);%, tracer_pos);
		hold on
		xlabel('Longitude [deg]')
		ylabel('Geopotential height [km]')
    	end % if FTLE_flag
    end % for subplotind = 1:2
    %--------------------------------------------------
    % Find the longitudinal plane closest to the desired plane.
    lon_ind = find(abs(lon - lon_plane) == min(abs(lon - lon_plane)));
    lat_wrapped = lat;
    
    % Plot the meridional plane with FTLE values on it.
    fignum = 2;
    figure(fignum)
    for subplotind = 1:2
    	nexttile
    	if FTLE_flag || tracer_flag
		if FTLE_flag
		    % Set this matrix to be nlev x nlat x 2?
		    FTLE_Value_lonslice = squeeze(FTLE_Value(:,lon_ind,:))';%, [3 1 2]);
		    % Need to be double or function delaunay doesn't work.
		    % Also needs to be nlev x nlat 
		    ht_inlonplane = double(squeeze(ht(lon_ind,:,:,1)))';
		    h = plot_meridional_ftle_map([ '('... 
		        prefixstr((filenum-1)*2+subplotind) ') ' ...
			datasource_str{subplotind} ...
			contour_str{fignum} ... modelstr
			], t0(1), plev, ht_inlonplane, lat, FTLE_Value_lonslice, lon_plane);
		    hold on
		    xlabel('Latitude [deg]')
		    ylabel('Geopotential height [km]')
		end % if FTLE_flag
	end % if FTLE_flag || tracer_flag
    end % for subplotind = 1:2
end % for filenum = 1:2

% All subplots should have FTLE maps on them now.

% Loop back over all subplots and overlay WACCMX+DART and SABER contours.
for filenum = 1:2
    % Go back to fig 1 and overlay WACCMX+DART on subplot 1.
    figure(1)
    nexttile((filenum-1)*2+1);

    Z3 = double(ncread(ncfilename{filenum}, 'Z3'))/1e3;
    waccmlat = ncread(ncfilename{filenum}, 'lat');
    waccmlon = ncread(ncfilename{filenum}, 'lon');

    % Eddy GPH is found by taking Z3 at midnight (optional: subtract off the mean at each grid point first), then subtract the zonal mean of Z3 over latitude 65 N.
    latind = find(abs(waccmlat - lat_plane) == min(abs(waccmlat - lat_plane)));
    waccmgph = squeeze(Z3(:,latind,:));
    zonalmeanZ3 = squeeze(mean(Z3,1));
    zonalmeanZ3_latslice = squeeze(zonalmeanZ3(latind,:));

    % Convert eddygph back to m.
    eddygph = 1e3*(waccmgph - repmat(zonalmeanZ3_latslice,size(waccmgph,1),1));

    % Select 21 levels from -2000 to 2000.
    offset = -min(min(eddygph))+1;%5e3*2;
    neglevel = [-2000:200:0] + offset;
    poslevel = [0:200:2000] + offset;
    % Make longitudes into a grid for plotting.
    longrid = repmat(waccmlon, 1, size(eddygph,2));

    % Plot contours on the same axes as the FTLE map.
    % Because the FTLE map is made with trisurf in 3D, the FTLE values
    % rise up off the z = 0 plane, so need to add some z depth here
    % to have the contour lines appear fully.
    contour3(longrid', waccmgph', eddygph'+offset, poslevel,'k');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)
    contour3(longrid', waccmgph', eddygph'+offset, neglevel,'w-');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)

	% Next tile to do the SABER comparison.
    % Go back to fig 1 and overlay saber.
    % Fig 1 subplot 2.
    nexttile((filenum-1)*2+2);
    % Overplot the SABER contours. Based on Lynn's email to SDB 8/26/26.
    % Select SABER eddy GPH. Dimensions are nlon x nsaber2_levs = [145 x 121]
    saberlon = double(ncread(saber{filenum}, 'LONGITUDE'));
    sabergph = double(ncread(saber{filenum}, 'SABER_GPH'));
    eddygph = double(ncread(saber{filenum}, 'SABER_EDDYGPH'));
    % Convert from m to km;
    eddygph = double(eddygph);

    % Select 21 levels from -2000 to 2000.
    offset = -min(min(eddygph))+1;%5e3*2;
    neglevel = [-2000:200:0] + offset;
    poslevel = [0:200:2000] + offset;
    % Make longitudes into a grid for plotting.
    longrid = repmat(saberlon, 1, size(eddygph,2));

    % Plot contours on the same axes as the FTLE map.
    % Because the FTLE map is made with trisurf in 3D, the FTLE values
    % rise up off the z = 0 plane, so need to add some z depth here
    % to have the contour lines appear fully.
    contour3(longrid', sabergph', eddygph'+offset, poslevel,'k');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)
    contour3(longrid', sabergph', eddygph'+offset, neglevel,'w-');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)

    % Next do the lat-alt comparison plot.
    figure(2);
    nexttile((filenum-1)*2+1);

    % Overplot the WACCMX+DART contours. Based on Nick's mtg SDB 9/22/26.
    lonind = find(abs(waccmlon - lon_plane) == min(abs(waccmlon - lon_plane)));
    clear waccmgph
    waccmgph = squeeze(Z3(lonind,:,:));
    U = double(ncread(ncfilename{filenum}, 'U'));
    waccmu = squeeze(U(lonind,:,:));
    % waccmgph and waccmu are 96x126.

    % Take zonal mean of U at each lat band and height, and can either do just 00:00 or avg over the day.
    zonal_ubar = squeeze(mean(U,1));

    offset = -min(min(waccmu))+1;%5e3*2;
    neglevel = [-100:10:0] + offset;
    poslevel = [0:10:100] + offset;
    % Make longitudes into a grid for plotting.
    latgrid = repmat(waccmlat, 1, size(waccmu,2));
    % Plot contours on the same axes as the FTLE map.
    % Because the FTLE map is made with trisurf in 3D, the FTLE values
    % rise up off the z = 0 plane, so need to add some z depth here
    % to have the contour lines appear fully.
    contour3(latgrid', waccmgph', zonal_ubar'+offset, poslevel,'k');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)
    contour3(latgrid', waccmgph', zonal_ubar'+offset, neglevel,'w-');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)

    % Overplot the SABER contours. Based on Lynn's email to SDB 8/26/26.
    nexttile((filenum-1)*2+2);
    saberlat = double(ncread(saber{filenum+2}, 'LATITUDE'));
    sabergph = double(ncread(saber{filenum+2}, 'SABER_GPH'));
    saberu = double(ncread(saber{filenum+2}, 'SABER_U'));

    offset = -min(min(saberu))+1;%5e3*2;
    neglevel = [-100:10:0] + offset;
    poslevel = [0:10:100] + offset;
    % Make longitudes into a grid for plotting.
    latgrid = repmat(saberlat, 1, size(saberu,2));
    % Plot contours on the same axes as the FTLE map.
    % Because the FTLE map is made with trisurf in 3D, the FTLE values
    % rise up off the z = 0 plane, so need to add some z depth here
    % to have the contour lines appear fully.
    contour3(latgrid', sabergph', saberu'+offset, poslevel,'k');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)
    contour3(latgrid', sabergph', saberu'+offset, neglevel,'w-');%,'LineWidth',2);%,saberlon,'k','LineWidth', 2)
end % for filenum = 1:2

% Save fig 1 as is.
figure(1)
lonfigfile = [output_dir datestr(now,'yymmdd') '_' ...
    modelstr '_' ...
    num2str(tarht/1e3) 'km_ftle_' filterstr 'lon-alt_' ...
    datestr(t0(1), 'yymmdd_hhMM') '_' ...
    datestr(t0(2), 'yymmdd_hhMM') '_' ...
    'waccmxdart_saber.fig'];
saveas(gcf,[lonfigfile(1:end-3) 'png'], 'png')
close

figure(2)
latfigfile = [output_dir datestr(now,'yymmdd') '_' ...
    modelstr '_' ...
    num2str(tarht/1e3) 'km_ftle_' filterstr 'lat-alt_' ...
    datestr(t0(1), 'yymmdd_hhMM') '_' ...
    datestr(t0(2), 'yymmdd_hhMM') '_' ...
    'waccmxdart_saber.fig'];
saveas(gcf,[latfigfile(1:end-3) 'png'], 'png')
close

