% This script loads and plots subfigures of difference slices of
% an ITALCS3Datmo 3D FTLE map/tracer set.
%
% S. Datta-Barua
% 7 Oct 2026 Preparing for publication to github.

clear

% Specify the path where the ITALCS3D run resultant netcdf files were placed.
run_folder = '/path/to/italcs3d/output/';

% Option 1 for input FTLE maps
% Specify the date that the ITALCS3D run was completed.
date_of_run{1} = 'yymmdd'; %'261007'; %
date_of_run{2} = 'yymmdd'; %'261007'; %

% Filenames of FTLE.nc files generated by waccm_italcs3d_script.m
fname{1} = [ run_folder date_of_run{1} '_runs/WACCMX+DART_ITALCS3Datmo_20090125_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
fname{2} = [ run_folder date_of_run{2} '_runs/WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Option 2 for FTLE maps
% Alternatively, use the files posted to zenodo.
fname{1} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090125_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
fname{2} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Specify a figure output path.
output_dir = '/path/to/figure/output/folder/';
if ~exist(output_dir,'dir')
    mkdir(output_dir)
end
%---------------------
% No need to change anything below here.

modelstr = 'WACCMX+DART';

FTLE_flag = 1;
tracer_flag = 1;
plev_flag = 0;
lon_plane = 315; % deg E
lat_plane = 65; % deg N
highres_flag = 2;
% Set filterstr for filename saving.
if highres_flag == 2
    filterstr = 'hrlyassim';
elseif highres_flag == 1
    filterstr = 'highres';
else
    filterstr = '6hrassim';
end

J_in_Cartesian_flag = 1;%[0 2 1 1]; % True if you want to transform to Jtilde, otherwise false.
prefixstr = 'abcd';

% Load hourly assimilation 2D FTLE outputs.
lat = ncread(fname{1}, 'lat');
lon = ncread(fname{1}, 'lon');
plev = ncread(fname{1},'plev');

clear FTLE_Value tracer_pos
if FTLE_flag
    FTLE_Value = ncread(fname{1}, 'FTLE');
end
try
    tracer_pos = ncread(fname{1}, 'tracer_pos');
    %	ht = ncread(fname{subplot_idx}, 'ht');
catch
    tracerlat = ncread(fname{1}, 'tracerlat');
    tracerlon = ncread(fname{1}, 'tracerlon');
    tracer_pos(:,2,:) = tracerlat;
    tracer_pos(:,1,:) = tracerlon;
end

if ~exist('modelstr', 'var')
    modelstr = 'WACCMX+DART';
end
if ~exist('t0', 'var')
    year = 2009;
    mon = 1;
    day = 25;
    hr = 0;
    minute = 0;
    sec = 0;
    t0 = datenum([year, mon, day, hr, minute, sec]);
end
if ~exist('trueht', 'var')
    trueht = 90; %km
    tarht = 90e3; %m
end
if ~exist('regionstr', 'var')
    regionstr = 'North Pole';
    origin = [90, 0]; % plot north pole at the center, 0 UT local time at the bottom
end
try
    ncread(fname{1}, 'filterstr');
catch
    filterstr = '';
end

try
    %if ~exist('integration_hours', 'var')
    integration_hours = ncread(fname{1}, 'integration_hours');
catch
    integration_hours = [24];%[24; 24; 24];
end
try
    FTLE_flag = ncread(fname{1}, 'FTLE_flag');
catch
    FTLE_flag = 1;
end
try
    ht = ncread(fname{1}, 'ht');
    htrow = find(abs(ht(1,1,:,1) - tarht) == min(abs(ht(1,1,:,1) - tarht)));
catch
    htrow = 57;
end

%% Begin plotting
tiledlayout(2,1, 'Padding', 'compact', 'TileSpacing', 'compact');
% Subplot (a): lat-alt plane at 315 deg E.
nexttile;
subplot_idx = 1;
%--------------------------------------------------
% Plot the meridional plane with FTLE values on it.
% Find the longitudinal plane closest to the desired plane.
lon_ind = find(abs(lon - lon_plane) == min(abs(lon - lon_plane)));
lat_wrapped = lat;
if FTLE_flag || tracer_flag

    if FTLE_flag
        % Set this matrix to be nlev x nlat x 2?
        FTLE_Value_lonslice = squeeze(FTLE_Value(:,lon_ind,:))';%, [3 1 2]);
        % Need to be double or function delaunay doesn't work.
        % Also needs to be nlev x nlat
        ht_inlonplane = double(squeeze(ht(lon_ind,:,:,1)))';
        h = plot_meridional_ftle_map([ '(' prefixstr(subplot_idx) ') ' modelstr], t0(1), plev, ht_inlonplane, lat, FTLE_Value_lonslice, lon_plane);
    end % if FTLE_flag
    if tracer_flag
        % Convert vertical units to km if z coordinate is gph.
        if plev_flag
            hA = plot_tracers(squeeze(tracer_pos(:,2,:)), ...
                squeeze(tracer_pos(:,3,:)));
            ylabel('Pressure level [hPa]')
        else
            hA = plot_tracers(squeeze(tracer_pos(:,2,:)), ...
                squeeze(tracer_pos(:,3,:)/1e3));
            ylabel('Geopotential height [km]')
        end % if plev_flag
        xlabel('Latitude [deg]')
    end % if tracer_flag

    % Subplot (b): lon-alt plane at 65 deg N.
    nexttile;
    subplot_idx = 2;
    % Plot the zonal plane with FTLE values on it.
    if FTLE_flag || tracer_flag
        if FTLE_flag
        	% Find the latitudinal plane closest to the desired plane.
        	lat_ind = find(abs(lat - lat_plane) == min(abs(lat - lat_plane)));
        	% Set this matrix to be nlev x nlon.
        	FTLE_Value_latslice = squeeze(FTLE_Value(lat_ind,:,:))';
        	% Need to be double or function delaunay doesn't work.
        	% Also needs to be nlev x nlon
        	ht_inlatplane = double(squeeze(ht(:,lat_ind,:,1)))';
        	h = plot_zonal_ftle_map(['(' prefixstr(subplot_idx) ') ' modelstr], t0(1), plev, ht_inlatplane, lon, FTLE_Value_latslice, lat_plane);%, tracer_pos);
        end % if FTLE_flag
        if tracer_flag
        	% Convert vertical units to km if z coordinate is gph.
        	if plev_flag
                hA = plot_tracers(squeeze(tracer_pos(:,1,:)), ...
                	squeeze(tracer_pos(:,3,:)));
        	    ylabel('Pressure level [hPa]')
            else
        	    hA = plot_tracers_unwrapped(squeeze(tracer_pos(:,1,:)), ...
                	squeeze(tracer_pos(:,3,:)/1e3));
        		ylabel('Geopotential height [km]')
        	end % if plev_flag
        	xlabel('Longitude [deg]')
        end	% if tracer_flag
    end % if FTLE_flag || tracer_flag

end

clear figfile
figfile = [output_dir datestr(now,'yymmdd') '_' ...
    modelstr '_' datestr(t0(1), 'yymmdd_hhMM') '_' ...
    num2str(integration_hours(1)) 'hr_' ...
    num2str(tarht/1e3) 'km_ftle_' filterstr '_slices-of-3d.fig'];
saveas(gcf,[figfile(1:end-3) 'png'], 'png')
close
