% This script loads and plots
% an ITALCS3Datmo tracer set on a longitude-time
% plot (Hovmoller diagram). This makes Fig 8 of the 2026 ITALCS3D paper.
%
% S. Datta-Barua
% 7 Oct 2026 Preparing for publication to github.

clear

% Specify the path where the ITALCS3D run resultant netcdf files were placed.
run_folder = '/path/to/italcs3d/output/';

% Option 1 for input FTLE maps
% Specify the date that the ITALCS3D run was completed.
date_of_run{1} = 'yymmdd'; %'261007'; %
date_of_run{2} = 'yymmdd'; %'261007'; %

% Filenames of FTLE.nc files generated by waccm_italcs3d_script.m
fname{1} = [ run_folder date_of_run{1} '_runs/WACCMX+DART_ITALCS3Datmo_20090125_168hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
%fname{2} = [ run_folder date_of_run{2} '_runs/WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Option 2 for FTLE maps
% Alternatively, use the files posted to zenodo.
fname{1} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090125_168hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];
%fname{2} = [ run_folder 'WACCMX+DART_ITALCS3Datmo_20090129_24hr_90km_hrlyassim_uvw111_JcartFTLE.nc'];

% Specify a figure output path.
output_dir = '/path/to/figure/output/folder/';
if ~exist(output_dir,'dir')
    mkdir(output_dir)
end

%---------------------
% No need to change anything below here.

FTLE_flag = 0; % Gets replaced by an attempt to read FTLE_flag from file.
tracer_flag = 1;
plev_flag = 0;
%lon_plane = 315; % deg E
lat_plane = 65; % deg N
highres_flag = 2;
% Set filterstr for filename saving.
if highres_flag == 2
    filterstr = 'hrlyassim';
elseif highres_flag == 1
    filterstr = 'highres';
else
    filterstr = '6hrassim';
end
J_in_Cartesian_flag = 1;%[0 2 1 1]; % True if you want to transform to Jtilde, otherwise false.


lat = ncread(fname{1}, 'lat');
lon = ncread(fname{1}, 'lon');
plev = ncread(fname{1},'plev');

clear FTLE_Value tracer_pos
if FTLE_flag
    FTLE_Value = ncread(fname{1}, 'FTLE');
end

try
    tracer_pos = ncread(fname{1}, 'tracer_pos');
catch
    tracerlat = ncread(fname{1}, 'tracerlat');
    tracerlon = ncread(fname{1}, 'tracerlon');
    tracer_pos(:,2,:) = tracerlat;
    tracer_pos(:,1,:) = tracerlon;
end


if ~exist('modelstr', 'var')
    modelstr = 'WACCMX+DART';
end
try
    t0 = ncread(fname{1}, 't0');
catch %if ~exist('t0', 'var')

    year = 2009;
    mon = 1;
    day = 25;
    hr = 0;
    minute = 0;
    sec = 0;
    t0 = datenum([year, mon, day, hr, minute, sec]);
end
if ~exist('trueht', 'var')
    trueht = 90; %km
    tarht = 90e3; %m
end

try
    ncread(fname{1}, 'filterstr');
catch
    filterstr = '';
end

try
    integration_hours = ncread(fname{1}, 'integration_hours');
catch
    integration_hours = [24];%[24; 24; 24];
end
try
    FTLE_flag = ncread(fname{1}, 'FTLE_flag');
catch
    FTLE_flag = 1;
end
try
    ht = ncread(fname{1}, 'ht');
    htrow = find(abs(ht(1,1,:,1) - tarht) == min(abs(ht(1,1,:,1) - tarht)));
catch
    htrow = 57;
end

% Construct a time coordinate. Matlab is recommending datetime instead of datenum.
t0_datetime = datetime(datevec(t0));
t_datetime = t0_datetime + hours(0:integration_hours);

%% Begin plotting
tiledlayout(1,2, 'Padding', 'compact', 'TileSpacing', 'compact');
nexttile;
% The ITALCS3D run initialized tracers every 10 deg longitude, but that is
% too crowded on the Hovmoller, so use every other for a 20-deg spacing.
subsampleind = 1:2:size(tracer_pos,3);

if tracer_flag
    % Convert vertical units to km if z coordinate is gph.
    if plev_flag
        hA = plot_tracers(squeeze(tracer_pos(:,1,:)), ...
            squeeze(tracer_pos(:,3,:)));
        ylabel('Pressure level [hPa]')
    else
        % Plot with GPH as color.
        colormap hsv
        hA = plot_tracers_hovmoller(squeeze(tracer_pos(:,1,subsampleind)), ...
    	    repmat(t_datetime',1,numel(subsampleind)), ...
    	    squeeze(tracer_pos(:,3,subsampleind)/1e3));
        ylabel('Time');
        clear c
        c = colorbar;
        c.Label.String = 'GPH [km]';
        xlabel('Longitude [deg]')
        title('(a)')% Plot of tracers initialized at 65^\circ N')
        % Plot with latitude as color.
        nexttile;
        colormap hsv
        hA = plot_tracers_hovmoller(squeeze(tracer_pos(:,1,subsampleind)), ...
    	    repmat(t_datetime',1,numel(subsampleind)), ...
            squeeze(tracer_pos(:,2,subsampleind)));
        ylabel('Time')
        clear c
        c = colorbar;
        c.Label.String = 'Latitude [deg N]';
        xlabel('Longitude [deg]')
        title('(b)')% Longitude-time-latitude plot of tracers initialized at 65^\circ N')
    end % if plev_flag
end	% if tracer_flag

clear figfile
figfile = [output_dir datestr(now,'yymmdd') '_' ...
    modelstr '_' datestr(t0(1), 'yymmdd_hhMM') '_' ...
    num2str(integration_hours(1)) 'hr_' ...
    num2str(tarht/1e3) 'km_ftle_' filterstr '_hovmoller.fig'];
saveas(gcf,[figfile(1:end-3) 'png'], 'png')
close
